# Generated by Django 3.1.4 on 2020-12-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellyourstory',
            name='poi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TellYourStories', to='core.pointofinterest'),
        ),
    ]
