# Generated by Django 3.1.4 on 2020-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_of_interest',
            name='comments',
        ),
        migrations.AddField(
            model_name='point_of_interest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
