# Generated by Django 3.1.4 on 2020-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellyourstory',
            name='image',
        ),
        migrations.AddField(
            model_name='tellyourstory',
            name='images',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
