# Generated by Django 3.1.4 on 2021-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210101_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='tellyourstory',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
