# Generated by Django 3.1.5 on 2021-01-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210105_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tellyourstory',
            name='username',
        ),
    ]
