# Generated by Django 3.1.4 on 2020-12-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201216_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point_of_interest',
            new_name='PointOfInterest',
        ),
    ]
