# Generated by Django 3.1.4 on 2021-01-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210101_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tellyourstory',
            name='username',
        ),
    ]
