# Generated by Django 3.1.5 on 2021-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210105_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tellyourstory',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
