# Generated by Django 3.1.5 on 2021-01-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210101_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='tellyourstory',
            name='username',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
