# Generated by Django 3.1.5 on 2021-01-08 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210106_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='PointsOfInterest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tellyourstory',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='TellYourStories', to=settings.AUTH_USER_MODEL),
        ),
    ]
